### ISSUE TITLE
Fatal: Unknown scheme: ARGON2

### ISSUE THREAD

**Issue by jamesbond0007** [LuckyFellow/dovecot-libsodium-plugin#2]
Hey guys any idea why after a good build and install scrypt is working but not argon2??

`root@server17771:~# doveadm pw -l
MD5 MD5-CRYPT SHA SHA1 SHA256 SHA512 SMD5 SSHA SSHA256 SSHA512 PLAIN CLEAR CLEARTEXT PLAIN-TRUNC CRAM-MD5 SCRAM-SHA-1 HMAC-MD5 DIGEST-MD5 PLAIN-MD4 PLAIN-MD5 LDAP-MD5 LANMAN NTLM OTP SKEY RPA PBKDF2 CRYPT SHA256-CRYPT SHA512-CRYPT SCRYPT 

root@server17771:~# dovecot --version
2.2.27 (c0f36b0)`

`root@server17771:~# doveadm -Dv pw -s ARGON2

Debug: Loading modules from directory: /usr/lib/dovecot/modules/doveadm
Debug: Skipping module doveadm_acl_plugin, because dlopen() failed: /usr/lib/dovecot/modules/doveadm/lib10_doveadm_acl_plugin.so: undefined symbol: acl_lookup_dict_iterate_visible_next (this is usually intentional, so just ignore this message)
Debug: Skipping module doveadm_expire_plugin, because dlopen() failed: /usr/lib/dovecot/modules/doveadm/lib10_doveadm_expire_plugin.so: undefined symbol: expire_set_deinit (this is usually intentional, so just ignore this message)
Debug: Skipping module doveadm_quota_plugin, because dlopen() failed: /usr/lib/dovecot/modules/doveadm/lib10_doveadm_quota_plugin.so: undefined symbol: quota_user_module (this is usually intentional, so just ignore this message)
Debug: Module loaded: /usr/lib/dovecot/modules/doveadm/lib10_doveadm_sieve_plugin.so
Debug: Skipping module doveadm_fts_lucene_plugin, because dlopen() failed: /usr/lib/dovecot/modules/doveadm/lib20_doveadm_fts_lucene_plugin.so: undefined symbol: lucene_index_iter_deinit (this is usually intentional, so just ignore this message)
Debug: Skipping module doveadm_fts_plugin, because dlopen() failed: /usr/lib/dovecot/modules/doveadm/lib20_doveadm_fts_plugin.so: undefined symbol: fts_user_get_language_list (this is usually intentional, so just ignore this message)
Debug: Skipping module doveadm_mail_crypt_plugin, because dlopen() failed: /usr/lib/dovecot/modules/doveadm/libdoveadm_mail_crypt_plugin.so: undefined symbol: mail_crypt_box_get_pvt_digests (this is usually intentional, so just ignore this message)
Debug: Loading modules from directory: /usr/lib/dovecot/modules/auth
Debug: Skipping module authdb_imap, because dlopen() failed: /usr/lib/dovecot/modules/auth/libauthdb_imap.so: undefined symbol: auth_request_ref (this is usually intentional, so just ignore this message)
Debug: Skipping module driver_mysql, because dlopen() failed: /usr/lib/dovecot/modules/auth/libdriver_mysql.so: undefined symbol: sql_transaction_add_query (this is usually intentional, so just ignore this message)
Debug: Module loaded: /usr/lib/dovecot/modules/auth/libsodium_plugin.so

Enter new password: 
Retype new password: 
Fatal: Unknown scheme: ARGON2`

**Comment by duritong** [comment]
What is your libsodium version? Argon2 support was added in libsodium 1.0.9
