### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by sasjafor** [LuckyFellow/dovecot-libsodium-plugin#4]
When I try to compile the source it seems that the needed header files are missing, like lib.h. I would be glad if @LuckyFellow could help with this issue.

**Comment by LuckyFellow** [comment]
Please check, whether this helps you: https://stackoverflow.com/questions/25026263/dovecot-plugin-deleted-to-trash-misses-lib-h-make-fails#25027869

Generally spoken, you need to provide (install) the dovecot-dev package, which includes the required header files.

**Comment by sasjafor** [comment]
Thanks for your answer. I figured it out now. It wasn't clear to me which path to point the --with-dovecot option to. For me it was /usr/lib/dovecot.
